// src/components/angular/theme-toggle.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-theme-toggle',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule],
  template: `
    <button
      mat-icon-button
      (click)="toggleTheme()"
      [attr.aria-label]="'切换主题'"
      class="theme-toggle-btn"
    >
      <mat-icon class="theme-icon">
        {{ isDark ? 'light_mode' : 'dark_mode' }}
      </mat-icon>
    </button>
  `,
  styles: [`
    .theme-toggle-btn {
      transition: transform 0.2s;
    }

    .theme-toggle-btn:hover {
      transform: scale(1.1);
    }

    .theme-icon {
      transition: transform 0.2s;
    }
  `]
})
export class ThemeToggleComponent implements OnInit, OnDestroy {
  isDark = false;

  ngOnInit() {
    if (typeof window !== 'undefined') {
      const savedTheme = localStorage.getItem('theme') as 'light' | 'dark' | null;
      const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      this.isDark = savedTheme ? savedTheme === 'dark' : prefersDark;
      document.documentElement.classList.toggle('dark', this.isDark);

      // Notify Giscus about theme change (delayed to ensure iframe is loaded)
      this.notifyGiscus();
      setTimeout(() => this.notifyGiscus(), 500);
      setTimeout(() => this.notifyGiscus(), 1500);
    }
  }

  ngOnDestroy() {
    // Cleanup if needed
  }

  toggleTheme() {
    if (typeof window === 'undefined') return;
    
    this.isDark = !this.isDark;
    document.documentElement.classList.toggle('dark', this.isDark);
    localStorage.setItem('theme', this.isDark ? 'dark' : 'light');
    
    // Notify Giscus about theme change
    this.notifyGiscus();
    
    // Dispatch theme changed event
    this.dispatchThemeChanged();
  }

  private sendGiscusMessage(message: object) {
    if (typeof window === 'undefined') return;
    
    const iframe = document.querySelector('iframe.giscus-frame') as HTMLIFrameElement;
    if (iframe?.contentWindow) {
      iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
    }
  }

  private notifyGiscus() {
    const theme = this.isDark ? 'dark' : 'light';
    this.sendGiscusMessage({
      setConfig: { theme }
    });
  }

  private dispatchThemeChanged() {
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('md3-theme-changed'));
    }
  }
}

// src/components/react/ThemeToggle.tsx
'use client';

import { useState, useEffect } from 'react';
import { ToggleButton } from 'react-aria-components';

interface ThemeToggleProps {
  className?: string;
}

// 发送消息给 Giscus
function sendGiscusMessage(message: object) {
  const iframe = document.querySelector('iframe.giscus-frame') as HTMLIFrameElement;
  if (iframe?.contentWindow) {
    iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
  }
}

// 派发主题变化事件，供其他组件监听
function dispatchThemeChanged() {
  window.dispatchEvent(new CustomEvent('md3-theme-changed'));
}

export function ThemeToggle({ className = '' }: ThemeToggleProps) {
  const [isDark, setIsDark] = useState(false);

  useEffect(() => {
    const savedTheme = localStorage.getItem('theme') as 'light' | 'dark' | null;
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    const initialIsDark = savedTheme ? savedTheme === 'dark' : prefersDark;
    setIsDark(initialIsDark);
    document.documentElement.classList.toggle('dark', initialIsDark);

    // 通知 Giscus 主题变化（延迟执行确保 iframe 已加载）
    const notifyGiscus = () => {
      const theme = initialIsDark ? 'dark' : 'light';
      sendGiscusMessage({
        setConfig: { theme }
      });
    };

    // 尝试多次通知，因为 Giscus iframe 可能还没加载
    notifyGiscus();
    const timeout = setTimeout(notifyGiscus, 500);
    const timeout2 = setTimeout(notifyGiscus, 1500);

    return () => {
      clearTimeout(timeout);
      clearTimeout(timeout2);
    };
  }, []);

  const toggleTheme = () => {
    const newIsDark = !isDark;
    setIsDark(newIsDark);
    document.documentElement.classList.toggle('dark', newIsDark);
    localStorage.setItem('theme', newIsDark ? 'dark' : 'light');
    
    // 通知 Giscus 主题变化
    const theme = newIsDark ? 'dark' : 'light';
    sendGiscusMessage({
      setConfig: { theme }
    });
    
    // 派发主题变化事件，让其他组件（如 ColorPicker）可以响应
    dispatchThemeChanged();
  };

  return (
    <ToggleButton
      isSelected={isDark}
      onPress={toggleTheme}
      className={`md-icon-button text-[var(--color-md-on-surface-variant)] focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-[var(--color-md-primary)] rounded-full transition-colors ${className}`}
      aria-label="切换主题"
    >
      <span className="material-symbols-outlined theme-icon transition-transform duration-200">
        {isDark ? 'light_mode' : 'dark_mode'}
      </span>
    </ToggleButton>
  );
}
