// src/app/components/view-count.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

@Component({
  selector: 'app-view-count',
  standalone: true,
  imports: [CommonModule, MatIconModule, MatProgressSpinnerModule],
  template: `
    <div class="view-count">
      <mat-icon class="view-icon">visibility</mat-icon>
      <span *ngIf="!loading" class="count">{{ views }}</span>
      <mat-spinner *ngIf="loading" diameter="16"></mat-spinner>
    </div>
  `,
  styles: [`
    .view-count {
      display: inline-flex;
      align-items: center;
      gap: 0.25rem;
      font-size: 0.875rem;
      color: rgb(var(--md-sys-color-on-surface-variant));
    }

    .view-icon {
      font-size: 18px;
      width: 18px;
      height: 18px;
    }

    .count {
      font-weight: 500;
    }

    mat-spinner {
      display: inline-block;
    }
  `]
})
export class ViewCountComponent implements OnInit {
  @Input() slug: string = '';
  views: number = 0;
  loading: boolean = true;

  async ngOnInit() {
    if (this.slug) {
      await this.fetchViewCount();
      await this.incrementViewCount();
    }
  }

  private async fetchViewCount() {
    try {
      const response = await fetch(`/api/views/${this.slug}`);
      if (response.ok) {
        const data = await response.json();
        this.views = data.views || 0;
      }
    } catch (error) {
      console.error('Failed to fetch view count:', error);
    } finally {
      this.loading = false;
    }
  }

  private async incrementViewCount() {
    try {
      const response = await fetch(`/api/views/${this.slug}`, {
        method: 'POST',
      });
      if (response.ok) {
        const data = await response.json();
        this.views = data.views || this.views;
      }
    } catch (error) {
      console.error('Failed to increment view count:', error);
    }
  }
}

// src/components/react/ViewCount.tsx
'use client';

import { useState, useEffect, useRef } from 'react';

interface ViewCountProps {
  slug: string;
  showLabel?: boolean;
  icon?: boolean;
}

export function ViewCount({ slug, showLabel = true, icon = true }: ViewCountProps) {
  const [count, setCount] = useState<number | null>(null);
  const [loading, setLoading] = useState(true);
  const fetchedRef = useRef(false);

  useEffect(() => {
    // Prevent double fetch in React Strict Mode
    if (fetchedRef.current) return;
    fetchedRef.current = true;

    async function fetchCount() {
      try {
        // Increment view
        const postResponse = await fetch(`/api/views/${slug}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' }
        });
        if (!postResponse.ok) throw new Error('Failed to increment');
        
        // Get updated count
        const getResponse = await fetch(`/api/views/${slug}`);
        if (!getResponse.ok) throw new Error('Failed to fetch');
        const data = await getResponse.json();
        setCount(data.views);
      } catch (e) {
        console.warn('Failed to fetch view count:', e);
        setCount(0);
      } finally {
        setLoading(false);
      }
    }

    fetchCount();
  }, [slug]);

  if (loading) {
    return (
      <span className="inline-flex items-center gap-1 text-[var(--color-md-on-surface-variant)] label-medium">
        {icon && <span className="material-symbols-outlined text-xs animate-pulse">visibility</span>}
        <span className="w-8">...</span>
      </span>
    );
  }

  const displayCount = count !== null ? formatCount(count) : '0';

  return (
    <span className="inline-flex items-center gap-1 text-[var(--color-md-on-surface-variant)] label-medium">
      {icon && <span className="material-symbols-outlined text-xs">visibility</span>}
      {showLabel && <span>{displayCount} 次阅读</span>}
      {!showLabel && <span>{displayCount}</span>}
    </span>
  );
}

function formatCount(count: number): string {
  if (count >= 10000) {
    return (count / 10000).toFixed(1) + '万';
  }
  if (count >= 1000) {
    return (count / 1000).toFixed(1) + 'k';
  }
  return count.toString();
}
